name: Sync To Gitee
on: page_build
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Jason-xy/jason-xy.github.io"
          destination-repo: "git@gitee.com:jason-xy/jason-xy.gitee.io"
      
      # - uses: mizuka-wu/gitee-pages-action@v1.0.0
      #   with:
      #       repository: jason-xy/jason-xy.gitee.io
      #       cookie: ${{ secrets.GITEE_COOKIE }} 
      #       directory: docs
      #       https: true